# Generated by Django 5.0.14 on 2025-04-26 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categoria', '0002_alter_categoria_options_alter_producto_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
