# Generated by Django 5.0.14 on 2025-04-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('nom_categoria', models.CharField(db_column='nom_categoria', max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_material', models.AutoField(db_column='cod_material', primary_key=True, serialize=False)),
                ('nom_producto', models.CharField(max_length=50)),
                ('cant_existencia', models.IntegerField()),
                ('descripcion', models.CharField(db_column='descripcion', max_length=50)),
                ('stock_minimo', models.IntegerField(default=20)),
                ('stock_maximo', models.IntegerField(default=100)),
                ('categoria_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
            },
        ),
    ]
